### PR TITLE
Makefile: more flexible `make install`

### PR DESCRIPTION
**Pull request by dunn**
Also bumped the version to current, in a separate commit.

### CODE REVIEW

**Comment by Necior** [comment]
Why not bump to 1.10?

**Comment by dunn** [comment]
Oh, I was just bringing it up to the stable version listed here: http://www.vanheusden.com/rsstail/

**Comment by Necior** [comment]
Oh, I missed it. Thanks for clarification.

**Comment by flok99** [comment]
Thanks!

**Pull request merged**
